name: Build and Test PHP App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t php-test-app .

    - name: Run Docker Container
      run: docker run -d -p 8080:80 --name php-test-container php-test-app

    - name: Wait for container to be ready and test homepage
      run: |
        for i in {1..10}; do
          echo "⏳ Attempt $i - Checking if index.php is reachable..."
          if curl --fail http://localhost:8080/index.php; then
            echo "✅ Success: index.php loaded!"
            break
          else
            echo "❌ Not yet available, waiting..."
            sleep 3
          fi
        done
